--新建数据库示例：

CREATE TABLE `pos_tb` (
`pos_id`  bigint NOT NULL AUTO_INCREMENT,
`pos_year`  varchar(255) CHARACTER SET utf8mb4 NULL COMMENT '年' ,
`pos_month`  varchar(255) CHARACTER SET utf8mb4 NULL COMMENT '月' ,
`pos_week_char`  varchar(255) CHARACTER SET utf8mb4 NULL COMMENT '周' ,
`pos_sche`  varchar(255) CHARACTER SET utf8mb4 NULL COMMENT '档期' ,
`pos_week_num`  int NULL COMMENT '周_数值' ,
`pos_brand_cn`  varchar(255) CHARACTER SET utf8mb4 NULL COMMENT '品牌_cn' ,
`pos_brand_en`  varchar(255) CHARACTER SET utf8mb4 NULL COMMENT '品牌_en' ,
`pos_category_id`  int NULL COMMENT '品类id' ,
`pos_category_desc`  varchar(255) CHARACTER SET utf8mb4 NULL COMMENT '品类描述' ,
`pos_dept_id`  int NULL COMMENT '部门id' ,
`pos_dept_desc`  varchar(255) CHARACTER SET utf8mb4 NULL COMMENT '部门描述' ,
`pos_class_id`  int NULL COMMENT '类id' ,
`pos_class_desc`  varchar(255) CHARACTER SET utf8mb4 NULL COMMENT '类描述' ,
`pos_supplier_id`  int NULL COMMENT '供应商id' ,
`pos_supplier_desc`  varchar(255) CHARACTER SET utf8mb4 NULL COMMENT '供应商描述' ,
`pos_item_code`  int NULL COMMENT '产品code' ,
`pos_item_desc`  varchar(255) CHARACTER SET utf8mb4 NULL COMMENT '产品描述' ,
`pos_bar_code`  bigint NULL COMMENT '条码' ,
`pos_is_seasonal`  varchar(255) CHARACTER SET utf8mb4 NULL COMMENT '季节性？' ,
`pos_is_pog`  varchar(255) CHARACTER SET utf8mb4 NULL COMMENT '待确认' ,
`pos_region_cn`  varchar(255) CHARACTER SET utf8mb4 NULL COMMENT '区域_中文' ,
`pos_mkt_cn`  varchar(255) CHARACTER SET utf8mb4 NULL COMMENT '市场_cn' ,
`pos_province`  varchar(255) CHARACTER SET utf8mb4 NULL COMMENT '省' ,
`pos_city`  varchar(255) CHARACTER SET utf8mb4 NULL COMMENT '市' ,
`pos_sales_store_id`  int NULL COMMENT 'Sales Store ID' ,
`pos_sales_store_name`  varchar(255) CHARACTER SET utf8mb4 NULL COMMENT 'Sales Store Name' ,
`pos_online_flg`  varchar(255) CHARACTER SET utf8mb4 NULL COMMENT 'Sales Store Online Flag' ,
`pos_order_store_id`  int NULL COMMENT 'Order Store ID' ,
`pos_order_store_name`  varchar(255) CHARACTER SET utf8mb4 NULL COMMENT 'Order Store Name' ,
`pos_deliver_store_id`  int NULL COMMENT 'Deliver Store ID' ,
`pos_deliver_store_name`  varchar(255) CHARACTER SET utf8mb4 NULL COMMENT 'Order Store Name' ,
`pos_sales_quantity`  varchar(255) NULL COMMENT '销售数量_Sales Quantity' ,
`pos_no_tax`  varchar(255) NULL COMMENT 'POS未税' ,
`pos_sales_amt_vat`  varchar(255) NULL COMMENT 'Sales Amt Include Vat' ,
`pos_srp`  float NULL COMMENT 'SRP' ,
`pos_price`  varchar(255) NULL COMMENT '零售价' ,
`pos_price_amt`  varchar(255) NULL COMMENT '零售价POS Amt未税' ,
`pos_channel_1`  varchar(255) CHARACTER SET utf8mb4 NULL COMMENT 'Channel 1' ,
`pos_channel_2`  varchar(255) CHARACTER SET utf8mb4 NULL COMMENT 'Channel 2' ,
`pos_tier`  varchar(255) CHARACTER SET utf8mb4 NULL COMMENT 'City Tier' ,
PRIMARY KEY (`pos_id`)
)
;

--插入数据示例